# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 02b91eb28f2939a3eabfb000e0039bb1c4aeb72eac5c92f5a9440f66e0f141c2f997c2813fd0b78f8a9d6c5f742c9d6ec9f87ad1f9bbaf680f9de14ce401396b

test:
  secret_key_base: a63e660a139eff6b5f512be0ed7e4ee47c03ea35f96421ab6cfcb34e18650c1415e9898fbd2c1fe041398087f2f0927e8bad21eb69bf295dff34d5e837098559

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
